name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v2
        with:
          ref: output # Checkout the 'output' branch where the snake gif will be pushed

      # Generate the snake gif
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ericz02
          gif_out_path: dist/github-contribution-grid-snake.gif # Update to the correct gif filename
          svg_out_path: dist/github-contribution-grid-snake.svg # Update to the correct svg filename

      # Commit the generated gif
      - name: Commit generated gif
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.gif
          git commit -m "Update snake gif [skip ci]"
      
      # Push changes to the output branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
